#server port
server:
    port: 9091

#spring setting
spring:
    output:
        ansi:
            enabled: always
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: TIS
        password: 1234

    thymeleaf:
        cache: false

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB

logging:
    level:
        root: INFO
        "[com.mk01.ProjectMK01]": DEBUG

mybatis:
    mapper-locations: classpath:mapper/sqlmapper/**/*.xml
    config-location: classpath:mapper/config/config.xml

file:
    path: C:/project01/upload/
